### PR TITLE
Spoiler flags

### PR DESCRIPTION
**Pull request by change1331**
Puts starting location, ship location, boss and other flag icons on the map and in the sidebar details.  Adds settings to allow toggling both items and flags.

### CODE REVIEW

**Comment by blkerby** [comment]
Some initial thoughts:

- I'm not sold yet on showing flag icons on the map. With the toggle option it seems close to being ok, but overall it still seems too messy. The user can already click the room to show the route for obtaining the flag, so the flag icons are not really necessary. They may be a bit more intuitive for new users, but it seems like there's too much of a drawback in how they obscure map tiles and get cut off by the black overlay. I think I prefer that they be removed along with the "items" and "flags" checkboxes. It might be different if the icons were smaller so they could consistently fit within the bounds of their room (or only very slightly overflow), still unsure.
- Having the flag icons in the side panel is definitely useful so let's keep that.
- Start location icon is also definitely great to have.
- I'm not sure about the Ship icon; it looks cool but functionally I'm not sure what it adds?
- The `startOffsets` object will be at high risk of getting broken if we modify the set of start locations in the future. I would prefer that the start coordinates be plumbed in through the spoiler JSON from the Rust side, so then it removes the need for this object. I can work on adding that.

**Comment by kjbranch** [comment]
Maddo and I had some different feelings on this one, so I thought I would share mine here.
- I think that the checkbox for the items is actually kind of nice and is worth keeping. While I agree that the icons are too cluttery, I would propose keeping the checkbox for them and having it set off by default.
- I would remove the Zebes cameras, and maybe split the rest into two toggles: Bosses (which would include minis) and Flags?
- I'm sure this is already planned, but many of the icons are too small to see, especially when in the side pannel: I would crop them much tighter (i.e. just Samus' head instead of her body, and some of the rest similar how the tracker looks) and make them square (some, like the tube, take a lot of space on the flags).
- Maybe this should be for a future PR, but it would be nice if clicking the start location showed the route to the starting hub, and maybe the escape route should be shown when clicking the ship.

**Comment by change1331** [comment]
Thanks for the feedback should've put wip on this one. I was thinking maybe

-  instead of all flags on minimap only the main objectives should be shown? another thing for the rust to spoiler.json unless they are already there and I missed them?
- I was already thinking of subcategories for the settings like majors/Xs/Os/all for items and flags can be separated into main objectives/optional.
- Icons still definitely need more iteration some work much better than others. Shape of room plays a major role in this too.
- definitely will add start pos to hub maybe add highlight to hub room popup will get text designation as hub room and click through same as start pos?
- escape route for ship is good idea, and will show the animals flag when route is displayed if rescue is req/optional

Will continue working on this in a little bit.

**Comment by blkerby** [comment]
Another thought is that we could add a (gear-shaped) settings button in the side panel, which could open a modal for toggling settings. Then they don't have to permanently occupy space in the top-right, and we can feel more free to split up the various settings or add more as needed. I'm not sure where the settings button would go relative to the (existing) info button or if those might be combined into a single modal; there are lots of possibilities here. Another thing is we can save the settings to local storage so that players can keep their preferred settings without having to set them every time.

**Comment by kjbranch** [comment]
Separating out the specific objective icons based on what is required for the seed sounds like it might be kind of difficult? But also might not be necessary, since the objective X's are easily located.

I think a settings cog and locally saving the users settings both sound great.

**Comment by blkerby** [comment]
>     * instead of all flags on minimap only the main objectives should be shown?

The most common scenario where players want to know how to obtain a flag are where it can only be cleared from one side of the room but clearing it opens passage both directions. Crocomire's Room is the example that comes up most frequently, and it doesn't really have to do with it being an objective or not. What happens is that the spoiler route for a progression item on that step shows cutting through Crocomire's Room from the left, but players don't understand how to clear Crocomire in the first place to be able to do that. So regardless of objectives, having the Crocomire icon there can help players see that there's something to click for how to clear Crocomire. Other flags where this same kind of thing can happen would be Spore Spawn, Botwoon, and Acid Chozo. In the current map pools (especially Tame) it doesn't seem to come up much with Acid Chozo, though that may change in the future.

I'm not sure I'm seeing the value of splitting off objectives from other flags? Plumbing that information through into the spoiler JSON can make sense in any case; it may be useful for other purposes.

>     * definitely will add start pos to hub maybe add highlight to hub room popup will get text designation as hub room and click through same as start pos?

Having an icon for hub room in addition to start location can be helpful; players are commonly confused about how this works.

**Comment by change1331** [comment]
I was just thinking of when there are non-standard objectives for the spoiler.json.  Settings cog is definitely the way to go.

**Pull request closed without merging**
