### PR TITLE
My patches (mostly fixes)

### PR DESCRIPTION
**Pull request by H-A-M-G-E-R**

### CODE REVIEW

**Comment by blkerby** [comment]
- Unsure about removing the hurt sound with zero-energy sparks. I can see the idea of trying to create more coherence in the game behavior; the hurt sound is mainly associated with energy loss, so with there no longer being energy loss it can make sense to remove the sound. On the other hand, in vanilla, the hurt sound still plays even if you don't lose energy (e.g. if already at 29 or below) so it can be consistent to just keep it. I'd lean toward keeping it vanilla unless there is a more compelling reason to change it.
- The simpler vertical doors fix is interesting. Do we know if swapping the order of those two calls will have any other effect on the game? At this stage of the randomizer's development, changing something like this feels a bit risky; given that the existing solution is working, I'm not sure we have much to gain from changing it? Unless there is some problem that you've observed or know about? If nothing else, looks like something to keep in mind for future projects.
- Can you explain more about what you are fixing in the MSU patch? Is it addressing some problem that has been observed or reported? I'm not sure how to quickly check exactly what song numbers get played in the game, so it's not easy to verify the modifications in this PR.

**Comment by H-A-M-G-E-R** [comment]
For my MSU-1 fix, the wrong track plays when Ceres explodes with Samus on it.

**Comment by H-A-M-G-E-R** [comment]
And the sound that plays when you have not enough energy for shinespark is an indication sound that you don't have enough energy, not losing energy.

**Comment by blkerby** [comment]
> For my MSU-1 fix, the wrong track plays when Ceres explodes with Samus on it.

That would explain the bank_2D change? But what about the other two changes, in bank_00 and bank_33?

**Comment by H-A-M-G-E-R** [comment]
In bank 00, there's a third unused song, and in bank 33, there's only 1 song.

**Comment by blkerby** [comment]
Cool, thinking about this some more, the shinespark sound change seems fitting. The MSU-1 and vertical door fixes are not expected to have any observable effect on the randomizer (e.g. since Ceres is skipped), but seem harmless. The simplicity of the new vertical door fix is appealing, so seems good to try it out; we can have this on the dev site for a while to watch for any potential issues.

**Pull request merged**
